### ISSUE TITLE
Crash when attempting to load several levels.

### ISSUE THREAD

**Issue by ChildishGiant** [Luffyyy/BeardLib-Editor#546] opened 2020-09-09 14:12 UTC
**Describe the crash**
When trying to load any of the follow levels I crash.
```
heist_pal / pal Counterfeit
heist_hox_3 / hox_3 The Revenge
heist_cage / cage Car Shop
```
**To Reproduce**
For me this is 100% reproduceable by attempting to load any of these levels.

**Crashlog**
```
Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/Utils.lua:96: attempt to index global 'BLEP' (a nil value)



SCRIPT STACK

HasProjectionLight() @mods/BeardLib-Editor/Classes/Utils.lua:342
HasAnyProjectionLight() @mods/BeardLib-Editor/Classes/Utils.lua:337
_setup_editor_unit_data() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:585
original() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:672
assign_unit_data() @mods/base/req/core/Hooks.lua:265
_create_statics_unit() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:659
create() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:196
create_world() core/lib/utils/dev/editor/worldholder.lua:110
init_game() lib/setups/gamesetup.lua:653
core/lib/setups/coresetup.lua:422


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
    Application version : 1.96.909
    CPU : AMD Ryzen 5 1600X Six-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
    DirectX : 12.0 
    GPU : Radeon (TM) RX 480 Graphics / aticfx32.dll[27.20.12027.1001]
    Language : english
    Memory :     16316MB 604KB
    OS : 6.2.9200 () 0x100-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Microsoft (Speakers (High Definition Audio Device))
```

**Comment by PONYMODZ** [comment] 2020-10-07 00:26
I have a similar crash, but always no matter what heist I load

```
Application has crashed: C++ exception
[string "lib/managers/blackmarketmanager.lua"]:6259: table index is nil



SCRIPT STACK

done_cb() lib/units/weapons/newraycastweaponbase.lua:230
clbk_part_unit_loaded() lib/managers/weaponfactorymanager.lua:869
assemble_from_blueprint() lib/managers/weaponfactorymanager.lua:636
assemble_from_blueprint() lib/units/weapons/newraycastweaponbase.lua:134
add_unit_by_factory_name() lib/units/beings/player/playerinventory.lua:223
_internal_load() lib/managers/playermanager.lua:678
spawned_player() lib/managers/playermanager.lua:959
set_unit() lib/network/base/networkpeer.lua:2338
spawn_unit() lib/network/base/networkpeer.lua:2241
spawn_players() lib/network/base/basenetworksession.lua:1513
update() lib/states/ingamewaitingforplayers.lua:293
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
original() lib/setups/setup.lua:880
update() @mods/base/req/core/Hooks.lua:188
original() lib/setups/gamesetup.lua:718
update() @mods/base/req/core/Hooks.lua:265
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[27.21.14.5655]
	Language : english
	Memory :     16343MB 472KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))
```

**Comment by MiamiCenterPL** [comment] 2020-11-15 20:24
@PONYMODZ Your game is crashing becouse game is failing to spawn weapon. Probably you're using Custom Weapons, that causes these crashes.

**Comment by Luffyyy** [comment] 2021-04-07 14:37
1) Cannot reproduce
2) This seems more like the DLL BLE uses failed to load or something, anyway this DLL will most likely be removed soon due to new features making it more or less obsolete. So wait for that commit, it will close this issue (if I don't forget)

**Closed** 2021-07-05 17:00 UTC
Labels: crash
