### ISSUE TITLE
[Crash] Cannot rotate camera + viewport

### ISSUE THREAD

**Issue by Dushess** [Luffyyy/BeardLib-Editor#418] opened 2019-09-28 08:02 UTC
Tested via angle value changing - instant crash with little delay
`Current thread: Main
Script stack:
               recalc_locals()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:718  
           recalc_all_locals()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:711  
                 select_unit()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:897  
               mouse_pressed()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:74  
                 mouse_press()  @mods/BeardLib-Editor/Classes/MapEditor.lua:283     
                 mouse_press()  487                                                 
                                lib/managers/mousepointermanager.lua:339     `

This happens because I changing angle on script-points, props can be operated safely.
Also guaranteed crash on object renaming (turning one object into another w/o spawning new and aligning on place of old one). Happening only if you didn't save map right before.

**Comment by ontrigger** [comment] 2019-10-26 13:31
Cannot reproduce, I also have no idea what you mean by object renaming

**Comment by Dushess** [comment] 2019-10-29 18:20
Put a cursore in unit name textbox, change path + name to another unit. See the unit swapping or crash. And for 1st - I gonna check without other mods.

**Comment by Luffyyy** [comment] 2020-01-11 18:52
Make a detailed issue for the other issue, do not combine issues. I am closing it for now until you will return with result of the check.

**Closed by Luffyyy** 2020-01-11 18:52 UTC
