### ISSUE TITLE
[Lighting] Some units not hiding on lights being baked

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#447] opened 2020-01-14 11:54 UTC
In the image below you can see the shelf is still casting a shadow even when the Hide On Projection Light is toggled on.

units/payday2/props/off_prop_generic_shelf_wire/off_prop_generic_shelf_wire_a

![20200114195053_1](https://user-images.githubusercontent.com/26837908/72342467-71b1d500-3707-11ea-9e52-055d328d4ceb.jpg)

**Comment by ontrigger** [comment] 2020-01-15 10:21
Cannot reproduce, try saving the game before building lights

**Comment by RexTheWho** [comment] 2020-01-17 03:32
Ive restarted the game, replaced props, ticked and unticked the shadow options. Nothing worked.

Here's a copy if you want to try.
[kosugi_v2.zip](https://github.com/Luffyyy/BeardLib-Editor/files/4074917/kosugi_v2.zip)

**Comment by RexTheWho** [comment] 2020-01-17 03:35
FOUND THE ISSUE!
It was in a portal, causes its hide on shadow projection setting to be overridden.

**Comment by Luffyyy** [comment] 2021-04-08 15:36
Fixed by disabling portal manager when generating stuff

**Closed** 2021-04-08 15:35 UTC
Labels: bug
